### ISSUE TITLE
Some bugs / inconsistencies

### ISSUE THREAD

**Issue by MoonlightSentinel** [Moth-Tolias/fixedstring#1]
Bugs:
1. Missings bounds checking in
  - `this(in char[])`
  - `opIndexAssign` (might extend `length` past `maxSize`
2. `opIndex` discards length by returning `char[maxSize]` (should probably return a slice)
3. `concat` doesn't check if  `s` is big enough

Enhancements:
1. slice assignments instead of plain loops
2. forward `fixedstring` methods to the slice ones instead of copying the implementation? (depends on 2.)

(Meta issue because I'm lazy)

**Comment by Moth-Tolias** [comment]
by bounds checking you mean the `in (rhs.length <= maxSize)` check, right? i'll get on that.

what do you mean by slice assignments instead of loops?

**Comment by MoonlightSentinel** [comment]
> by bounds checking you mean the `in (rhs.length <= maxSize)` check, right? i'll get on that.

Yes

> what do you mean by slice assignments instead of loops?

```d
foreach (i, char c; rhs)
{
	data[i] = c;
}
```

is nearly identical to

```d
data[] = rhs[];
```

but more readable

**Comment by Moth-Tolias** [comment]
that should fix everything, i think!
