### ISSUE TITLE
Feature Request: FixedString from literal with automatic length

### ISSUE THREAD

**Issue by pbackus** [Moth-Tolias/fixedstring#2]
Currently, to create a `FixedString` from a string literal, we have to pass the length explicitly:

```d
enum literal = "hello";
FixedString!(literal.length) s = literal;
```

It would be convenient if there was a helper template that calculated the length automatically, so that we could instead write code like this:

```d
auto s = fixedString!"hello";
```

**Comment by Moth-Tolias** [comment]
implemented =]
